
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed contenedorPrincipal;

	private global::Gtk.Label labelNombre;

	private global::Gtk.Label labelApellido;

	private global::Gtk.Label labelTelefono;

	private global::Gtk.Label labelCorreo;

	private global::Gtk.Entry entryNombre;

	private global::Gtk.Entry entryApellido;

	private global::Gtk.Entry entryCorreo;

	private global::Gtk.Entry entryTelefono;

	private global::Gtk.Button btnGuardar;

	private global::Gtk.Button btnEliminar;

	private global::Gtk.Button btnNuevo;

	private global::Gtk.Table tabla;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.contenedorPrincipal = new global::Gtk.Fixed();
		this.contenedorPrincipal.Name = "contenedorPrincipal";
		this.contenedorPrincipal.HasWindow = false;
		// Container child contenedorPrincipal.Gtk.Fixed+FixedChild
		this.labelNombre = new global::Gtk.Label();
		this.labelNombre.Name = "labelNombre";
		this.labelNombre.Xalign = 0F;
		this.labelNombre.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre");
		this.contenedorPrincipal.Add(this.labelNombre);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.contenedorPrincipal[this.labelNombre]));
		w1.X = 25;
		w1.Y = 28;
		// Container child contenedorPrincipal.Gtk.Fixed+FixedChild
		this.labelApellido = new global::Gtk.Label();
		this.labelApellido.Name = "labelApellido";
		this.labelApellido.Xalign = 0F;
		this.labelApellido.LabelProp = global::Mono.Unix.Catalog.GetString("Apellido");
		this.contenedorPrincipal.Add(this.labelApellido);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.contenedorPrincipal[this.labelApellido]));
		w2.X = 25;
		w2.Y = 68;
		// Container child contenedorPrincipal.Gtk.Fixed+FixedChild
		this.labelTelefono = new global::Gtk.Label();
		this.labelTelefono.Name = "labelTelefono";
		this.labelTelefono.Xalign = 0F;
		this.labelTelefono.LabelProp = global::Mono.Unix.Catalog.GetString("Telefono");
		this.contenedorPrincipal.Add(this.labelTelefono);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.contenedorPrincipal[this.labelTelefono]));
		w3.X = 25;
		w3.Y = 108;
		// Container child contenedorPrincipal.Gtk.Fixed+FixedChild
		this.labelCorreo = new global::Gtk.Label();
		this.labelCorreo.Name = "labelCorreo";
		this.labelCorreo.Xalign = 0F;
		this.labelCorreo.LabelProp = global::Mono.Unix.Catalog.GetString("Correo");
		this.contenedorPrincipal.Add(this.labelCorreo);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.contenedorPrincipal[this.labelCorreo]));
		w4.X = 25;
		w4.Y = 148;
		// Container child contenedorPrincipal.Gtk.Fixed+FixedChild
		this.entryNombre = new global::Gtk.Entry();
		this.entryNombre.CanFocus = true;
		this.entryNombre.Name = "entryNombre";
		this.entryNombre.IsEditable = true;
		this.entryNombre.InvisibleChar = '●';
		this.contenedorPrincipal.Add(this.entryNombre);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.contenedorPrincipal[this.entryNombre]));
		w5.X = 100;
		w5.Y = 23;
		// Container child contenedorPrincipal.Gtk.Fixed+FixedChild
		this.entryApellido = new global::Gtk.Entry();
		this.entryApellido.CanFocus = true;
		this.entryApellido.Name = "entryApellido";
		this.entryApellido.IsEditable = true;
		this.entryApellido.InvisibleChar = '●';
		this.contenedorPrincipal.Add(this.entryApellido);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.contenedorPrincipal[this.entryApellido]));
		w6.X = 100;
		w6.Y = 63;
		// Container child contenedorPrincipal.Gtk.Fixed+FixedChild
		this.entryCorreo = new global::Gtk.Entry();
		this.entryCorreo.CanFocus = true;
		this.entryCorreo.Name = "entryCorreo";
		this.entryCorreo.IsEditable = true;
		this.entryCorreo.InvisibleChar = '●';
		this.contenedorPrincipal.Add(this.entryCorreo);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.contenedorPrincipal[this.entryCorreo]));
		w7.X = 100;
		w7.Y = 143;
		// Container child contenedorPrincipal.Gtk.Fixed+FixedChild
		this.entryTelefono = new global::Gtk.Entry();
		this.entryTelefono.CanFocus = true;
		this.entryTelefono.Name = "entryTelefono";
		this.entryTelefono.IsEditable = true;
		this.entryTelefono.InvisibleChar = '●';
		this.contenedorPrincipal.Add(this.entryTelefono);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.contenedorPrincipal[this.entryTelefono]));
		w8.X = 100;
		w8.Y = 103;
		// Container child contenedorPrincipal.Gtk.Fixed+FixedChild
		this.btnGuardar = new global::Gtk.Button();
		this.btnGuardar.CanFocus = true;
		this.btnGuardar.Name = "btnGuardar";
		this.btnGuardar.UseUnderline = true;
		this.btnGuardar.Label = global::Mono.Unix.Catalog.GetString("Guardar");
		this.contenedorPrincipal.Add(this.btnGuardar);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.contenedorPrincipal[this.btnGuardar]));
		w9.X = 300;
		w9.Y = 79;
		// Container child contenedorPrincipal.Gtk.Fixed+FixedChild
		this.btnEliminar = new global::Gtk.Button();
		this.btnEliminar.CanFocus = true;
		this.btnEliminar.Name = "btnEliminar";
		this.btnEliminar.UseUnderline = true;
		this.btnEliminar.Label = global::Mono.Unix.Catalog.GetString("Eliminar");
		this.contenedorPrincipal.Add(this.btnEliminar);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.contenedorPrincipal[this.btnEliminar]));
		w10.X = 300;
		w10.Y = 135;
		// Container child contenedorPrincipal.Gtk.Fixed+FixedChild
		this.btnNuevo = new global::Gtk.Button();
		this.btnNuevo.CanFocus = true;
		this.btnNuevo.Name = "btnNuevo";
		this.btnNuevo.UseUnderline = true;
		this.btnNuevo.Label = global::Mono.Unix.Catalog.GetString("Nuevo");
		this.contenedorPrincipal.Add(this.btnNuevo);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.contenedorPrincipal[this.btnNuevo]));
		w11.X = 300;
		w11.Y = 19;
		// Container child contenedorPrincipal.Gtk.Fixed+FixedChild
		this.tabla = new global::Gtk.Table(((uint)(4)), ((uint)(3)), false);
		this.tabla.Name = "tabla";
		this.tabla.RowSpacing = ((uint)(6));
		this.tabla.ColumnSpacing = ((uint)(6));
		this.contenedorPrincipal.Add(this.tabla);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.contenedorPrincipal[this.tabla]));
		w12.X = 25;
		w12.Y = 190;
		this.Add(this.contenedorPrincipal);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 657;
		this.DefaultHeight = 355;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
